global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'acra-server'
    static_configs:
      - targets: ['acra-server:9399']
  - job_name: 'acra-connector'
    static_configs:
      - targets: ['acra-connector:9499']
